import com.android.build.api.dsl.ApplicationExtension
import com.android.build.api.variant.impl.VariantOutputImpl
import com.google.gson.JsonParser
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.jose4j.json.internal.json_simple.JSONObject
import java.io.DataInputStream
import java.io.File
import java.net.HttpURLConnection
import java.net.URI
import java.net.URL

plugins {
    alias(libs.plugins.agp.app)
    alias(libs.plugins.refine)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.nav.safeargs.kotlin)
}

/*
 * The Material 3 palettes and the ThemeOverlay.Light/Dark.Material* styles used by
 * ThemeUtils are checked in at src/main/res/values/md_theme_builder.xml. They used to be
 * generated by dev.rikka.tools.materialthemebuilder, which needs the AGP legacy DSL and
 * therefore cannot run with AGP 9's new `android { }` DSL.
 */

val appPackageName: String = rootProject.extra["appPackageName"] as String
val crowdinProjectId: String = rootProject.extra["crowdinProjectId"] as String
val crowdinApiKey: String = rootProject.extra["crowdinApiKey"] as String
val localBuild: Boolean = rootProject.extra["localBuild"] as Boolean
val officialBuild: Boolean = rootProject.extra["officialBuild"] as Boolean

afterEvaluate {
    // `android.sourceSets` hangs off the deprecated legacy extension, use the public
    // DSL type instead. The directories are project relative, unlike the File set the
    // legacy API returned.
    val assetsDir = extensions.getByType<ApplicationExtension>()
        .sourceSets["main"].assets.directories.firstOrNull() ?: "src/main/assets"
    val srcDir = File(assetsDir).let { if (it.isAbsolute) it else File(projectDir, it.path) }
    logger.lifecycle("Asset dir: $srcDir")
    if (!srcDir.exists()) srcDir.mkdirs()

    val translatorsMap = mutableMapOf(
        // I used GitHub to get translations before moving to Crowdin.
        // Since nearly all of GitHub translators are listed in Crowdin
        // too, I wanted to add one profile here.

        "cvnertnc" to "https://avatars.githubusercontent.com/u/148134890?v=4",
    )

    val urlConnection = if (crowdinApiKey.isNotBlank()) {
        val url = URI("https://crowdin.com/api/v2/projects/$crowdinProjectId/members").toURL()
        (url.openConnection() as HttpURLConnection).apply {
            setRequestProperty("authorization", "Bearer $crowdinApiKey")
        }
    } else {
        val url = URI("https://github.com/frknkrc44/HMA-OSS/releases/latest/download/translators.json").toURL()
        url.openConnection() as HttpURLConnection
    }

    val inputStream = DataInputStream(urlConnection.getInputStream())
    val str = String(inputStream.readAllBytes())
    inputStream.close()
    urlConnection.disconnect()

    val json = JsonParser.parseString(str).asJsonObject

    if (crowdinApiKey.isNotBlank()) {
        val translators = json.getAsJsonArray("data")

        for (item in translators) {
            val translator = item.asJsonObject.getAsJsonObject("data")
            val avatarUrl = translator.get("avatarUrl").asString
            val username = translator.get("username").asString
            val fullName = try {
                translator.get("fullName").asString
            } catch (_: Throwable) {
                ""
            }

            if (fullName.isNotEmpty() && fullName != username) {
                translatorsMap["$fullName ($username)"] = avatarUrl
            } else {
                translatorsMap[username] = avatarUrl
            }
        }
    } else {
        json.keySet().forEach { translatorsMap[it] = json.get(it).asString }
    }

    val translatorJson = JSONObject(translatorsMap).toJSONString()
    File(srcDir, "translators.json").writeText(translatorJson)
}

configure<ApplicationExtension> {
    namespace = appPackageName

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    packaging {
        dex.useLegacyPackaging = true
        resources {
            excludes += arrayOf(
                // NOTE: "/META-INF/xposed/**" must NOT be excluded, the Modern Xposed
                // framework reads java_init.list / module.prop / scope.list from there.
                "/META-INF/androidx/**",
                "/META-INF/com/**",
                "/META-INF/versions/**",
                "/META-INF/*.version",
                "/META-INF/*.kotlin_module",
                "/META-INF/*.kotlin_builtins",
                "/kotlin/**",
                "/okhttp3/**",
            )
        }
    }
}

kotlin {
    jvmToolchain(21)
}

/*
 * Locale list, replaces dev.rikka.tools.autoresconfig.
 *
 * The plugin scanned `values-*` directories, restricted the packaged locales through
 * `resConfigs` and generated the `LangList` class the language picker iterates over.
 * The scanning rule is kept identical: a directory counts when it contains a
 * non-placeholder `strings.xml` and its qualifier has at most three segments.
 */
fun localeModifiersOf(resDir: File): Set<String> {
    val modifiers = sortedSetOf(String.CASE_INSENSITIVE_ORDER)
    resDir.listFiles().orEmpty().forEach { dir ->
        if (!dir.isDirectory || !dir.name.startsWith("values-")) return@forEach
        val strings = File(dir, "strings.xml")
        if (!strings.isFile || strings.length() <= 62) return@forEach
        val modifier = dir.name.removePrefix("values-")
        if (modifier.split("-").size <= 3) modifiers.add(modifier)
    }
    // The default resources are English even though there is no values-en directory.
    modifiers.add("en")
    return modifiers
}

fun modifierToLocale(modifier: String): String {
    if (modifier.startsWith("b+")) {
        val names = modifier.removePrefix("b+").split("+", limit = 2)
        return if (names.size == 2) "${names[0]}-${names[1]}" else names[0]
    }
    val names = modifier.split("-", limit = 2)
    return if (names.size == 2) "${names[0]}-${names[1].removePrefix("r")}" else names[0]
}

/** Scripts the platform knows better than the raw resource qualifier. */
val displayLocaleOverrides = mapOf("zh-CN" to "zh-Hans", "zh-TW" to "zh-Hant")

val appResDir = layout.projectDirectory.dir("src/main/res").asFile
val localeModifiers = localeModifiersOf(appResDir)
val langListLocales = localeModifiers
    .map(::modifierToLocale)
    .sortedWith(String.CASE_INSENSITIVE_ORDER)
val langListDisplayLocales = langListLocales.map { displayLocaleOverrides[it] ?: it }

configure<ApplicationExtension> {
    defaultConfig {
        // Keep only the locales that actually have a translation, like resConfigs did.
        resourceConfigurations.addAll(localeModifiers)
    }
}

abstract class GenerateLangListTask : DefaultTask() {

    /** Resource root the locale list is derived from. */
    @get:Internal
    abstract val resDir: DirectoryProperty

    /** Only the locale string files, so unrelated resource edits do not rerun the task. */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val localeStrings: ConfigurableFileCollection

    @get:Input
    abstract val firstItem: Property<String>

    @get:Input
    abstract val locales: ListProperty<String>

    @get:Input
    abstract val displayLocales: ListProperty<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val packageName = "icu.nullptr.hidemyapplist.util"
        val target = outputDir.get().asFile
            .resolve(packageName.replace('.', '/'))
            .resolve("LangList.java")
        target.parentFile.mkdirs()

        fun array(values: List<String>) = values.joinToString(",") { "\"$it\"" }

        target.writeText(
            """
            |package $packageName;
            |
            |// Generated by the :app:generateLangList task, do not edit.
            |public final class LangList {
            |    public static final String[] LOCALES = {"${firstItem.get()}",${array(locales.get())}};
            |    public static final String[] DISPLAY_LOCALES = {"${firstItem.get()}",${array(displayLocales.get())}};
            |}
            |""".trimMargin()
        )
    }
}

val generateLangList = tasks.register<GenerateLangListTask>("generateLangList") {
    resDir.set(layout.projectDirectory.dir("src/main/res"))
    localeStrings.from(
        fileTree(layout.projectDirectory.dir("src/main/res")) { include("values-*/strings.xml") }
    )
    firstItem.set("SYSTEM")
    locales.set(langListLocales)
    displayLocales.set(langListDisplayLocales)
    outputDir.set(layout.buildDirectory.dir("generated/langList/java"))
}

dependencies {
    implementation(projects.common)
    runtimeOnly(projects.xposed)

    implementation(libs.androidx.navigation.fragment.ktx)
    implementation(libs.androidx.navigation.ui.ktx)
    implementation(libs.androidx.preference.ktx)
    implementation(libs.androidx.swiperefreshlayout)
    implementation(libs.com.github.bumptech.glide)
    implementation(libs.dev.androidbroadcast.vbpd)
    implementation(libs.dev.androidbroadcast.vbpd.reflection)
    implementation(libs.com.github.topjohnwu.libsu.core)
    implementation(libs.dev.rikka.hidden.compat)
    implementation(libs.me.zhanghai.android.appiconloader)
    implementation(libs.io.github.libxposed.service)
    compileOnly(libs.dev.rikka.hidden.stub)

    implementation(libs.androidx.appcompat.appcompat)
    implementation(libs.material)
}

androidComponents {
    onVariants { variant ->
        variant.sources.java?.addGeneratedSourceDirectory(generateLangList, GenerateLangListTask::outputDir)

        variant.outputs.forEach { output ->
            // `outputFileName` is only exposed by the AGP implementation type, the
            // public VariantOutput API does not cover output naming yet.
            (output as? VariantOutputImpl)?.outputFileName?.set(
                output.versionName.map { versionName ->
                    "${rootProject.name.replace(" ", "_")}-$versionName-${variant.buildType}.apk"
                }
            )
        }
    }
}
